### ISSUE TITLE
这个包写进了成像软件问题如下 

### ISSUE THREAD

**Issue by InnocentSmile** [DIYer22/hik_camera#4]
1. 相机ip 变动很麻烦
2. 打包之后报错①
找不到 MvCameraNode-CH.csvc  简直神奇  压根没这个文件 只有  hik_camera\MvCameraNode-CH.csv  我重命名结局了
4. 报错② Traceback (most recent call last):                                                                                        File "tabpage\main_imgshow_page.py", line 572, in on_off                                                                File "hik_camera\hik_camera.py", line 227, in get_cams                                                                    cams = MultiHikCamera({ip: cls(ip) for ip in ips})                                                                    File "hik_camera\hik_camera.py", line 227, in <dictcomp>                                                                  cams = MultiHikCamera({ip: cls(ip) for ip in ips})                                                                    File "hik_camera\hik_camera.py", line 89, in __init__                                                                     host_ip = get_host_ip_by_target_ip(ip)                                                                                File "hik_camera\hik_camera.py", line 45, in get_host_ip_by_target_ip                                                     for s in [socket.socket(socket.AF_INET, socket.SOCK_DGRAM)]                                                           File "hik_camera\hik_camera.py", line 45, in <listcomp>                                                                   for s in [socket.socket(socket.AF_INET, socket.SOCK_DGRAM)]                                                         socket.gaierror: [Errno 11001] getaddrinfo failed
5. 报错之后重新打开了一个新的程序窗口 真的很神奇

**Comment by DIYer22** [comment]
我手上没有设备了，难以支持，抱歉

**Comment by InnocentSmile** [comment]
好吧   那你现在 直接连接吗?

**Comment by DIYer22** [comment]
我是指我的工作换了，不太接触工业相机了，所以支持不了了 :cry:
